default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "census_rails") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "census_rails") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  timeout: 5000

development:
  <<: *default
  database: census_rails_development

test:
  <<: *default
  database: census_rails_test

production:
  <<: *default
  database: census_rails_production
  username: census_rails
  password: <%= ENV['CENSUS_RAILS_DATABASE_PASSWORD'] %>
